---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Robotex140.
--- Based on Zomboid RainCollectorBarrel
--- DateTime: 16-Jan-22 16:10
---

require "Map/CGlobalObject"

CBeehiveGlobalObject = CGlobalObject:derive("CBeehiveGlobalObject")

function CBeehiveGlobalObject:new(luaSystem, globalObject)
    local o = CGlobalObject.new(self, luaSystem, globalObject)
    return o
end

function CBeehiveGlobalObject:getObject()
    return self:getIsoObject()
end
